=== tamaranrt2017/ISTvezba3/autooglas.dtd
<!DOCTYPE AutoOglas [

<!ELEMENT AutoOglas (Automobil)+>
<!ELEMENT Automobil (Proizvodjac, Model, Godiste, Farba, ZapreminaMotora, Transmisija, Gorivo, Cena, KontaktProdavca)>
<!ELEMENT Proizvodjac (#PCDATA)>
<!ELEMENT Model (#PCDATA)>
<!ATTLIST Model tip CDATA #IMPLIED>
<!ELEMENT Godiste (#PCDATA)>
<!ELEMENT Farba (boja)>
<!ATTLIST Farba tip (akril | metalik) #REQUIRED>
<!ELEMENT ZapreminaMotora (#PCDATA)>
<!ATTLIST ZapreminaMotora jedinica (ccm | l) #IMPLIED> 
<!ELEMENT Transmisija (brojbrzina)>
<!ATTLIST Transmisija tip (manuelni | auto) #REQUIRED>
<!ELEMENT Gorivo (#PCDATA)>
<!ATTLIST Gorivo tng (da | ne) #IMPLIED>
<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena valuta (din | eur) #IMPLIED>
<!ELEMENT KontaktProdavca (#PCDATA)>
<!ELEMENT boja (#PCDATA)>
<!ELEMENT brojbrzina (#PCDATA)> ]>

=== tamaranrt2017/ISTvezba3/autooglas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE AutoOglas SYSTEM "autooglas.dtd"> 
<AutoOglas>
<Automobil>
<Proizvodjac>Honda</Proizvodjac>
<Model tip="SUV"> CR-V </Model>
<Godiste> 2015 </Godiste> 
<Farba tip="matalik"> <boja>Crna </boja> </Farba>
<ZapreminaMotora jedinica="ccm"> 1597</ZapreminaMotora>
<Transmisija tip="auto"> <brojbrzina> 6 brzina </brojbrzina></Transmisija>
<Gorivo tng="ne"> Dizel</Gorivo>
<Cena valuta="eur">13.600 </Cena>
<KontaktProdavca> Marko, 0611111111 </KontaktProdavca>
</Automobil>


<Automobil>
<Proizvodjac>Volkswagen</Proizvodjac>
<Model tip="Hecbek"> Golf6 </Model>
<Godiste> 2009 </Godiste> 
<Farba tip="matalik"> Bela</Farba>
<ZapreminaMotora jedinica="ccm"> 1968</ZapreminaMotora>
<Transmisija tip="manuelni"> 6 brzina</Transmisija>
<Gorivo tng="ne">Dizel </Gorivo>
<Cena valuta="eur">7.200 </Cena>
<KontaktProdavca> Milos, 0611111111 </KontaktProdavca>


</Automobil>
</AutoOglas>
