=== tamaranrt2017/ISTvezba3/zadatak5.dtd
<!DOCTYPE NEWSPAPER     
[
<!ELEMENT NEWSPAPER(ARTICLE+, FOOTER)>
<!ELEMENT FOOTER (#PCDATA)>
<!ELEMENT ARTICLE(HEADLINE, BYLINE, LEAD, BODY, NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT LEAD (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>
<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED
                 EDITOR  CDATA #IMPLIED
                 DATE CDATA #IMPLIED
                 EDITION CDATA #IMPLIED >
<!ENTITY NEWSPAPER "Politikin zabavnik">
<!ENTITY PUBLISHER"politika d.o.o" >
<!ENTITY COPYRIGHT "2015 Politikin zabavnik"> ]>

=== tamaranrt2017/ISTvezba3/zadatak5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NEWSPAPER SYSTEM "zadatak5.dtd"> 
<NEWSPAPER>
    <ARTICLE AUTHOR="" EDITOR="" DATE="" EDITION="">
        <HEADLINE> </HEADLINE>
        <BYLINE> </BYLINE>
        <LEAD> </LEAD>
        <BODY> </BODY>
        <NOTES> </NOTES>
    </ARTICLE>
<FOOTER>&NEWSPAPER;&PUBLISHER;&COPYRIGHT;</FOOTER>
</NEWSPAPER>
